version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  init-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install react react-dom
            - run: npm install
            - run: npm test
workflows:
  test:
    jobs:
      - init-and-test
